[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
name = "runtime-common"
version = "0.9.23"

[dependencies]
bitvec = {version = "1.0.0", default-features = false, features = ["alloc"]}
impl-trait-for-tuples = "0.2.2"
log = {version = "0.4.17", default-features = false}
parity-scale-codec = {version = "3.1.2", default-features = false, features = ["derive"]}
rustc-hex = {version = "2.1.0", default-features = false}
scale-info = {version = "2.1.2", default-features = false, features = ["derive"]}
static_assertions = "1.1.0"

sp-api = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}
sp-core = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}
sp-io = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}
sp-runtime = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}
sp-std = {package = "sp-std", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}

frame-support = {version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}
frame-system = {version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}
pallet-authorship = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}
pallet-balances = {version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
pallet-transaction-payment = {version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}
pallet-treasury = {version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false}

frame-benchmarking = {version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", default-features = false, optional = true}

gafi-primitives = {path = "../../primitives", default-features = false}

[dev-dependencies]
pallet-treasury = {version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-keystore = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
trie-db = "0.23.1"

[features]
default = ["std"]
no_std = []
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
std = [
  "bitvec/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "log/std",
  "rustc-hex/std",
  "sp-core/std",
  "sp-api/std",
  "sp-std/std",
  "sp-io/std",
  "frame-support/std",
  "pallet-transaction-payment/std",
  "pallet-treasury/std",
  "sp-runtime/std",
  "frame-system/std",
]
try-runtime = [
  "pallet-transaction-payment/try-runtime",
  "pallet-treasury/try-runtime",
]
