[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
description = "FRAME pallet template for defining custom runtime logic."
edition = "2021"
homepage = "https://substrate.io/"
license = "Unlicense"
name = "pallet-pool"
publish = false
repository = "https://github.com/grindytech/gafi"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
] }
log = { version = "0.4.16" }
scale-info = { version = "2.1.0", default-features = false, features = [
  "derive",
] }
serde = { version = "1.0.119" }

# Substrate
frame-benchmarking = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", optional = true }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
pallet-timestamp = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-io = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-core = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }

# Local
gafi-primitives = { version = "4.0.0-dev", default-features = false, path = "../../primitives" }
pallet-cache = { version = "4.0.0-dev", default-features = false, path = "../pallet-cache" }

[dev-dependencies]
sp-core = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-io = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
pallet-balances = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
pallet-randomness-collective-flip = { default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
staking-pool = { version = "4.0.0-dev", default-features = false, path = "../staking-pool" }
upfront-pool = { version = "4.0.0-dev", default-features = false, path = "../upfront-pool" }
sponsored-pool = { version = "4.0.0-dev", default-features = false, path = "../sponsored-pool" }
pallet-pool-names = { default-features = false, version = "4.0.0-dev", path = "../pool-names" }
pallet-cache = { default-features = false, version = "4.0.0-dev", path = "../pallet-cache" }


[features]
default = ["std"]
std = [
  "codec/std",
  "scale-info/std",
  "serde/std",
  "frame-support/std",
  "frame-system/std",
  "frame-benchmarking/std",
  "gafi-primitives/std",
  "sp-std/std",
  "sp-io/std",
  "pallet-timestamp/std",
  "pallet-cache/std",
  "sp-core/std",
  "pallet-balances/std",
  "upfront-pool/std",
  "staking-pool/std",
  "sponsored-pool/std",
  "pallet-cache/std",
  "pallet-randomness-collective-flip/std",
]

runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "gafi-primitives/runtime-benchmarks",
  "sponsored-pool/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
