[package]
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Node, ready for hacking together a parachain."
edition = "2021"
homepage = "https://substrate.io"
license = "Unlicense"
name = "gafi-local"
repository = "https://github.com/grindytech/cumulus/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1"
clap = {version = "3.1", features = ["derive"]}
codec = {package = "parity-scale-codec", version = "3.1", features = ["derive"]}
futures = '0.3'
hex-literal = '0.3'
jsonrpc-core = "18.0.0"
jsonrpc-pubsub = "18.0.0"
jsonrpsee = {version = "0.14.0", features = ["server", "macros"]}
log = "0.4.8"
serde_json = "1.0.59"

# Frontier
fc-cli = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fc-consensus = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fc-db = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fc-mapping-sync = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fc-rpc = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fc-rpc-core = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fp-consensus = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fp-dynamic-fee = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fp-evm = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fp-rpc = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
fp-storage = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
pallet-base-fee = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
pallet-dynamic-fee = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
pallet-ethereum = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}
pallet-evm = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.26"}

# Substrate
frame-system = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
pallet-transaction-payment = {default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-cli = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", features = ["wasmtime"]}
sc-client-api = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-consensus = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-consensus-aura = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", optional = true}
sc-consensus-manual-seal = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", optional = true}
sc-executor = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", features = ["wasmtime"]}
sc-finality-grandpa = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-keystore = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-network = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-service = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26", features = ["wasmtime"]}
sc-telemetry = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-transaction-pool = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-transaction-pool-api = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-consensus = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-consensus-aura = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-core = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-finality-grandpa = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-inherents = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-keyring = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-runtime = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-io = {default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-std = {default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-timestamp = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}

# These dependencies are used for the node template's RPCs
pallet-transaction-payment-rpc = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-basic-authorship = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-rpc = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sc-rpc-api = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-api = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-block-builder = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-blockchain = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
substrate-frame-rpc-system = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}

# These dependencies are used for runtime benchmarking
frame-benchmarking = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
frame-benchmarking-cli = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}

pallet-player = { version = "4.0.0-dev", default-features = false, path = "../../pallets/player" }
pallet-player-rpc-runtime-api = { version = "4.0.0-dev", default-features = false, path = "../../pallets/player/runtime-api" }

cumulus-primitives-core = {git = "https://github.com/grindytech/cumulus", branch = "gafi-polkadot-v0.9.26"}
session-keys-primitives = { git = "https://github.com/grindytech/moonbeam", default-features = false, branch = "gafi-polkadot-v0.9.26" }
nimbus-primitives = { git = "https://github.com/grindytech/nimbus", branch = "gafi-polkadot-v0.9.26", default-features = false }

sp-session = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-offchain = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
sp-transaction-pool = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}
pallet-transaction-payment-rpc-runtime-api = {version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}

# Local Dependencies
devnet = {path = "../../runtime/devnet", default-features = false, features = ["std"]}
gafi-primitives = {path = "../../primitives", default-features = false}

[build-dependencies]
substrate-build-script-utils = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.26"}

[features]
aura = [
  "sc-consensus-aura",
  "devnet/aura",
]
default = ["aura"]
manual-seal = [
  "sc-consensus-manual-seal",
  "devnet/manual-seal",
]

with-dev = [
  "devnet/with-dev"
]

rpc_binary_search_estimate = ["fc-rpc/rpc_binary_search_estimate"]
runtime-benchmarks = [
  "devnet/runtime-benchmarks",
]
