name: Docker build & push
on:
  push:
    tags: ["*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - run: chmod +x ./scripts/docker_build.sh
      - run: ./scripts/docker_build.sh ${{ secrets.DOCKERHUB_USERNAME }}/gafi-node:${{github.ref_name}}
      - run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/gafi-node:${{github.ref_name}} ${{ secrets.DOCKERHUB_USERNAME }}/gafi-node:latest
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gafi-node:latest
